# Use the container that comes with `cross` as a base. It's already got
# a cross-compile toolchain installed, so that's less work for us.
FROM ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:0.2.2

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install --assume-yes libdbus-1-dev:armhf libsystemd-dev:armhf libsystemd0:armhf

ENV PKG_CONFIG_PATH="/usr/lib/arm-linux-gnueabihf/pkgconfig/:${PKG_CONFIG_PATH}"
# ENV PKG_CONFIG_LIBDIR="/usr/lib/arm-linux-gnueabihf/pkgconfig"

# New!
# ENV PKG_CONFIG_LIBDIR_arm_unknown_linux_gnueabihf=/usr/lib/arm-linux-gnueabihf/pkgconfig
