name: Continuous Integration

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            command: cargo

          - target: aarch64-unknown-linux-gnu
            command: cross

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate version
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: |
          export CARGO_VERSION=v$(awk '/^version/ {print $3}' Cargo.toml | head -1 | tr -d '"')
          export GIT_VERSION=${{github.ref_name}}
          echo "$CARGO_VERSION and $GIT_VERSION"
          if [[ "${CARGO_VERSION}" != "$GIT_VERSION" ]]; then
            echo "Tag version and Cargo.toml version don't match" 1>&2
            exit 1
          fi

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: install dependencies
        run: sudo apt-get install -y libdbus-1-dev pkg-config

      - name: install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Run fmt command
        run: cargo fmt --all -- --check --color always

      - name: Run clippy command
        run: ${{matrix.platform.command}} clippy --all-targets --all-features --workspace -- -D warnings

      - name: Run build command
        run: ${{matrix.platform.command}} build --release --target ${{matrix.platform.target}}

      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        if: github.ref_type == 'tag'
        with:
          generateReleaseNotes: "true"
          assets: |
            - path: target/${{matrix.platform.target}}/release/tempsys-scan
              name: tempsys-scan-${{matrix.platform.target}}-${{ github.ref_name }}
