name: Continuous Integration

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Deps
        run: sudo apt-get install -y libdbus-1-dev pkg-config

      - name: Run fmt command
        run: cargo fmt --all -- --check --color always

      - name: Run clippy command
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  deploy:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate version
        run: |
          export CARGO_VERSION=v$(awk '/^version/ {print $3}' Cargo.toml | head -1 | tr -d '"')
          export GIT_VERSION=${{github.ref_name}}
          echo "$CARGO_VERSION and $GIT_VERSION"
          if [[ "${CARGO_VERSION}" != "$GIT_VERSION" ]]; then
            echo "Tag version and Cargo.toml version don't match" 1>&2
            exit 1
          fi

      - uses: cargo-bins/cargo-binstall@main

      - name: install cross
        run: cargo binstall --no-confirm cross

      - name: Run build command
        run: cross build --release --target ${{matrix.platform.target}}

      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        with:
          generateReleaseNotes: "true"
          assets: |
            - path: target/${{matrix.platform.target}}/release/tempsys-scan
              name: tempsys-scan-${{matrix.platform.target}}-${{ github.ref_name }}
